service: proto2-backend
frameworkVersion: "3"

custom:
  datapointTable: "datapoint-${sls:stage}"
  datapointTableDatapointIndex: "datapoint-${sls:stage}-datapointIndex"
  connectionsTable: "connections-${sls:stage}"
  connectionsTableVinIndex: "connections-${sls:stage}-vinIndex"
  vehiclesTable: "vehicles-${sls:stage}"
  dynamodb:
    stages:
      - dev
    start:
      port: 8002
      inMemory: true
      migrate: true
  serverless-offline-dynamodb-streams:
    endpoint: http://0.0.0.0:8002
    region: us-east-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false
    readInterval: 500

plugins:
  - serverless-webpack
  - serverless-offline-dynamodb-streams
  - serverless-offline
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [DataPointTable, Arn]
            # - Fn::Join:
            #     - "/"
            #     - - Fn::GetAtt: [Connections, Arn]
            #       - "index"
            #       - ${self:custom.datapointTableDatapointIndex}
            - Fn::GetAtt: [Connections, Arn]
            - Fn::Join:
                - "/"
                - - Fn::GetAtt: [Connections, Arn]
                  - "index"
                  - ${self:custom.connectionsTableVinIndex}
            - Fn::GetAtt: [VehiclesTable, Arn]

  environment:
    DATAPOINT_TABLE: ${self:custom.datapointTable}
    DATAPOINT_TABLE_DATAPOINT_INDEX: ${self:custom.datapointTableDatapointIndex}
    CONNECTIONS_TABLE: ${self:custom.connectionsTable}
    CONNECTIONS_TABLE_VIN_INDEX: ${self:custom.connectionsTableVinIndex}
    VEHICLES_TABLE: ${self:custom.vehiclesTable}

functions:
  api:
    handler: index.handler
    events:
      - httpApi: "*"
  # pullVehicles:
  #   handler: src/pullVehicles/handler.handler
  #   events:
  #     - schedule: rate(1 minute)
  pullVehicleData:
    handler: src/pullVehicleData/handler.handler
    events:
      - schedule: rate(1 minute)
  connect:
    handler: src/connect/handler.connect
    events:
      - websocket:
          route: $connect
          # npx wscat -c ws://localhost:3001
  disconnect:
    handler: src/disconnect/handler.disconnect
    events:
      - websocket:
          route: $disconnect
  dispatcher:
    handler: src/dispatcher/handler.dispatcher
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - DataPointTable
              - StreamArn

resources:
  Resources:
    Connections:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          # - AttributeName: vin
          #   AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.connectionsTable}
        # GlobalSecondaryIndexes:
        #   - IndexName: ${self:custom.connectionsTableVinIndex}
        #     Projection:
        #       ProjectionType: ALL
        #     KeySchema:
        #       - AttributeName: vin
        #         KeyType: HASH
    DataPointTable:
      Type: AWS::DynamoDB::Table
      Properties:
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        AttributeDefinitions:
          - AttributeName: vin
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
          - AttributeName: vinWithDataPointName
            AttributeType: S
        KeySchema:
          - AttributeName: vin
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.datapointTable}
        GlobalSecondaryIndexes:
        - IndexName: ${self:custom.datapointTableDatapointIndex}
          Projection:
            ProjectionType: ALL
          KeySchema:
            - AttributeName: vinWithDataPointName
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
    VehiclesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: vin
            AttributeType: S
        KeySchema:
          - AttributeName: vin
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.vehiclesTable}
